/**
 * Fonte ÚNICA do catálogo de permissões da VISIO.
 *
 * Daqui saem dois artefatos, por `npm run gen:permissions`:
 *   · src/lib/permissions/catalog.ts                        (tipos + catálogo p/ a UI)
 *   · supabase/migrations/*_visio_03b_permissoes_seed.sql   (seed + modelos padrão)
 *
 * Nunca edite os artefatos gerados: edite este arquivo e rode o gerador.
 *
 * Granularidade: uma chave por AÇÃO DE NEGÓCIO, não por módulo. É o que permite
 * dar a um vendedor "só consulta das próprias vendas" e a um gerente "gestão
 * completa" sem inventar cargos no código.
 *
 * `sensivel: true` significa que a chave também é checada na LEITURA (no RLS),
 * não só na escrita — custo, margem e dado financeiro entram aqui.
 */

export const modules = [
  {
    key: 'dashboard',
    label: 'Painel de Informações',
    icon: 'LayoutDashboard',
    acoes: [
      ['acessar', 'Acessar o painel'],
      ['card_vendas_mes', 'Card: vendas do mês'],
      ['card_vendas_12m', 'Card: últimos 12 meses'],
      ['card_comparativo_ano', 'Card: mesmo mês do ano anterior'],
      ['card_contas_pagar', 'Card: contas a pagar em aberto', null, true],
      ['card_contas_receber', 'Card: contas a receber em aberto', null, true],
      ['card_aniversariantes', 'Card: aniversariantes da semana'],
      ['card_receitas_vencidas', 'Card: receitas vencidas'],
      ['card_os_entregar', 'Card: O.S. a entregar'],
      ['card_validade_produtos', 'Card: validade de produtos'],
      ['card_estoque_minimo', 'Card: produtos abaixo do estoque mínimo'],
      ['card_negativados', 'Card: clientes negativados'],
      ['card_oportunidade_aberto', 'Card: oportunidade em aberto'],
    ],
  },
  {
    key: 'clientes',
    label: 'Clientes',
    icon: 'Users',
    acoes: [
      ['acessar', 'Acessar o menu Clientes'],
      ['consultar', 'Consultar clientes'],
      ['incluir', 'Incluir cliente'],
      ['alterar', 'Alterar cliente'],
      ['alterar_nome', 'Alterar o nome de um cliente já cadastrado'],
      ['excluir', 'Excluir cliente'],
      ['importar', 'Importar clientes em massa'],
      ['exportar', 'Exportar clientes'],
      ['exportar_receitas', 'Exportar receitas'],
      ['negativar', 'Negativar e remover negativação'],
      ['ver_credito', 'Ver situação de crédito e parcelas em atraso', null, true],
      ['analise_credito', 'Efetuar análise de crédito', 'Exige consentimento do titular; a decisão é sempre revisável por humano.', true],
      ['gerenciar_nucleo_familiar', 'Gerenciar núcleo familiar'],
    ],
  },
  {
    key: 'receitas',
    label: 'Receitas (prescrições)',
    icon: 'Eye',
    acoes: [
      ['consultar', 'Consultar receitas'],
      ['incluir', 'Incluir receita'],
      ['alterar', 'Alterar receita'],
      ['excluir', 'Excluir receita'],
      ['imprimir', 'Imprimir receita'],
      ['livro_receitas', 'Acessar o Livro de Receitas'],
    ],
  },
  {
    key: 'produtos',
    label: 'Produtos',
    icon: 'Package',
    acoes: [
      ['acessar', 'Acessar o menu Produtos'],
      ['consultar', 'Consultar produtos'],
      ['incluir', 'Incluir produto'],
      ['alterar', 'Alterar dados do produto'],
      ['excluir', 'Excluir ou arquivar produto'],
      ['ver_custo', 'Ver preço de custo', null, true],
      ['alterar_custo', 'Alterar preço de custo', null, true],
      ['alterar_preco', 'Alterar preço de venda'],
      ['alterar_estoque', 'Alterar quantidade em estoque'],
      ['alterar_validade', 'Alterar validade'],
      ['alterar_fiscal', 'Alterar configuração fiscal (NCM, CEST, tributação)'],
      ['importar', 'Importar produtos em massa'],
      ['exportar', 'Exportar produtos'],
      ['gerenciar_vitrine', 'Incluir e remover da vitrine online'],
    ],
  },
  {
    key: 'tabelas_lentes',
    label: 'Tabelas de Lentes',
    icon: 'Table2',
    acoes: [
      ['acessar', 'Acessar o menu Tabelas de Lentes'],
      ['consultar', 'Consultar tabelas'],
      ['salvar_conferencia', 'Salvar conferência de produtos'],
      ['concluir_conferencia', 'Concluir conferência'],
      ['ver_custo_fornecedor', 'Ver preço de custo do fornecedor', null, true],
      ['excluir_em_conferencia', 'Excluir tabela em conferência'],
    ],
  },
  {
    key: 'orcamentos',
    label: 'Orçamentos',
    icon: 'FileText',
    acoes: [
      ['consultar', 'Consultar todos os orçamentos'],
      ['consultar_proprios', 'Consultar somente os próprios orçamentos'],
      ['incluir', 'Incluir orçamento'],
      ['alterar', 'Alterar orçamento'],
      ['excluir', 'Excluir orçamento'],
      ['imprimir', 'Imprimir orçamento'],
      ['converter_venda', 'Converter orçamento em venda'],
      ['prorrogar_validade', 'Prorrogar a validade de um orçamento'],
    ],
  },
  {
    key: 'vendas',
    label: 'Vendas',
    icon: 'ShoppingCart',
    acoes: [
      ['consultar', 'Consultar todas as vendas'],
      ['consultar_proprias', 'Consultar somente as próprias vendas'],
      ['incluir', 'Incluir venda'],
      ['alterar', 'Alterar venda'],
      ['cancelar', 'Cancelar venda', 'Exige motivo obrigatório e fica na trilha de auditoria.'],
      ['excluir', 'Excluir venda', 'Exige motivo obrigatório e fica na trilha de auditoria.'],
      ['duplicar', 'Duplicar venda'],
      ['imprimir', 'Imprimir venda e relatórios'],
      ['ver_paineis', 'Ver painéis de resumo'],
      ['ver_margem', 'Ver margem de lucro', null, true],
      ['data_retroativa', 'Lançar com data retroativa'],
      ['alterar_valor_unitario', 'Alterar valor unitário do item'],
      ['autorizar_desconto_distancia', 'Autorizar desconto à distância'],
      ['alterar_funcionario', 'Alterar o funcionário vinculado'],
      ['alterar_convenio', 'Alterar o convênio vinculado'],
      ['alterar_origem', 'Alterar a origem do cliente vinculada'],
      ['gerenciar_garantia', 'Gerenciar validade do termo de garantia'],
      ['emitir_nfce', 'Emitir NFC-e'],
    ],
  },
  {
    key: 'ordens_servico',
    label: 'Ordens de Serviço',
    icon: 'ClipboardList',
    acoes: [
      ['consultar', 'Consultar todas as O.S.'],
      ['consultar_proprias', 'Consultar somente as próprias O.S.'],
      ['incluir', 'Incluir O.S.'],
      ['alterar', 'Alterar qualquer O.S.'],
      ['alterar_proprias', 'Alterar somente as próprias O.S.'],
      ['alterar_somente_abertas', 'Alterar somente O.S. abertas'],
      ['cancelar', 'Cancelar O.S.'],
      ['confirmar_perda', 'Confirmar O.S. em perda'],
      ['mover_etapa', 'Mover O.S. entre etapas do Kanban'],
      ['entregar', 'Entregar O.S.'],
      ['retornar_entregue', 'Retornar O.S. entregue para não entregue'],
      ['alterar_funcionario', 'Alterar o funcionário vinculado'],
      ['imprimir', 'Imprimir O.S.'],
      ['ver_paineis', 'Ver painéis de resumo'],
      ['data_retroativa', 'Abrir ou lançar com data retroativa'],
      ['gerenciar_etapas', 'Configurar tipos e etapas de O.S. (SLA por etapa)'],
    ],
  },
  {
    key: 'trocas',
    label: 'Trocas',
    icon: 'RefreshCw',
    acoes: [
      ['consultar', 'Consultar trocas'],
      ['iniciar', 'Iniciar troca'],
      ['cancelar', 'Cancelar troca'],
      ['utilizar_credito', 'Utilizar crédito de troca dentro do limite'],
      ['utilizar_credito_acima_limite', 'Utilizar crédito de troca acima do limite'],
      ['devolver_credito', 'Devolver crédito de troca'],
      ['inutilizar_credito', 'Inutilizar crédito de troca'],
    ],
  },
  {
    key: 'estoque',
    label: 'Estoque',
    icon: 'Boxes',
    acoes: [
      ['acessar', 'Acessar o menu Estoque'],
      ['posicao_atual', 'Consultar posição atual'],
      ['posicao_todas_filiais', 'Consultar a posição de todas as filiais'],
      ['entrada_nf', 'Dar entrada por XML de NF-e'],
      ['entrada_manual', 'Dar entrada manual'],
      ['transferir', 'Solicitar transferência entre filiais'],
      ['confirmar_transferencia', 'Confirmar recebimento de transferência'],
      ['inventario', 'Realizar inventário'],
      ['acerto', 'Fazer acerto de estoque'],
      ['etiquetas', 'Montar e imprimir etiquetas'],
      ['historico', 'Consultar histórico de movimentação'],
      ['zerar', 'Zerar estoque'],
      ['exportar', 'Exportar posição de estoque'],
    ],
  },
  {
    key: 'caixa',
    label: 'Caixa',
    icon: 'Wallet',
    acoes: [
      ['consultar', 'Consultar posição atual do caixa', null, true],
      ['abrir', 'Abrir caixa'],
      ['fechar', 'Fechar caixa'],
      ['reabrir', 'Reabrir caixa fechado'],
      ['pagar_despesa', 'Pagar despesas pelo caixa'],
      ['transferir', 'Transferir entre contas'],
      ['suprimento', 'Lançar suprimento'],
      ['sangria', 'Lançar sangria'],
      ['excluir_lancamento', 'Apagar lançamentos'],
      ['alterar_saldo_inicial', 'Alterar saldo inicial'],
    ],
  },
  {
    key: 'contas_pagar',
    label: 'Contas a Pagar',
    icon: 'TrendingDown',
    acoes: [
      ['consultar', 'Consultar contas a pagar', null, true],
      ['incluir', 'Incluir conta a pagar'],
      ['alterar', 'Alterar conta a pagar'],
      ['baixar', 'Baixar conta a pagar'],
      ['estornar', 'Estornar baixa'],
      ['cancelar', 'Cancelar conta a pagar'],
      ['imprimir', 'Imprimir'],
      ['data_retroativa', 'Lançar ou baixar com data retroativa'],
    ],
  },
  {
    key: 'contas_receber',
    label: 'Contas a Receber',
    icon: 'TrendingUp',
    acoes: [
      ['consultar', 'Consultar contas a receber', null, true],
      ['incluir', 'Incluir conta a receber'],
      ['alterar', 'Alterar conta a receber'],
      ['receber', 'Receber / baixar'],
      ['estornar', 'Estornar recebimento'],
      ['cancelar', 'Cancelar conta a receber'],
      ['imprimir', 'Imprimir'],
      ['data_retroativa', 'Lançar ou receber com data retroativa'],
      ['alterar_situacao', 'Alterar situação'],
      ['renegociar', 'Renegociar dívida'],
      ['autorizar_desconto_distancia', 'Autorizar desconto à distância'],
      ['baixar_outras_filiais', 'Baixar títulos de outras filiais da rede'],
    ],
  },
  {
    key: 'crediario',
    label: 'Crediário',
    icon: 'CreditCard',
    acoes: [
      ['consultar', 'Consultar crediários', null, true],
      ['conceder', 'Conceder crediário'],
      ['alterar_limite', 'Alterar limite do cliente'],
      ['baixar', 'Baixar parcela de crediário'],
      ['ver_score', 'Ver score e histórico de análise de crédito', null, true],
    ],
  },
  {
    key: 'cartao',
    label: 'Recebimentos Cartão',
    icon: 'CreditCard',
    acoes: [
      ['consultar', 'Consultar recebimentos de cartão', null, true],
      ['conciliar', 'Conciliar com a adquirente'],
      ['gerenciar_antecipacoes', 'Gerenciar antecipações'],
      ['alterar_taxa', 'Alterar taxa'],
      ['ver_liquido', 'Ver valor líquido e taxa descontada', null, true],
    ],
  },
  {
    key: 'cheques',
    label: 'Cheques',
    icon: 'Receipt',
    acoes: [
      ['consultar', 'Consultar cheques', null, true],
      ['incluir', 'Incluir cheque'],
      ['alterar_status', 'Alterar status (depositado, compensado, devolvido)'],
      ['devolver', 'Registrar devolução'],
      ['imprimir', 'Imprimir'],
    ],
  },
  {
    key: 'boletos',
    label: 'Boletos',
    icon: 'Barcode',
    acoes: [
      ['consultar', 'Consultar boletos', null, true],
      ['emitir', 'Emitir boleto'],
      ['cancelar', 'Cancelar boleto'],
      ['baixar', 'Baixar boleto'],
      ['ver_taxas', 'Ver taxas de emissão', null, true],
    ],
  },
  {
    key: 'cobranca_bancaria',
    label: 'Cobrança Bancária',
    icon: 'Landmark',
    acoes: [
      ['consultar', 'Consultar remessas e retornos', null, true],
      ['gerar_remessa', 'Gerar arquivo de remessa (CNAB)'],
      ['processar_retorno', 'Processar arquivo de retorno (CNAB)'],
      ['configurar', 'Configurar convênio de cobrança'],
    ],
  },
  {
    key: 'financeiro',
    label: 'Financeiro',
    icon: 'PiggyBank',
    acoes: [
      ['fluxo_financeiro', 'Consultar fluxo financeiro (previsto e realizado)', null, true],
      ['dre', 'Consultar Resultado (DRE)', null, true],
      ['configurar_dre', 'Configurar o DRE'],
      ['plano_contas', 'Gerenciar plano de contas'],
      ['contas_bancarias', 'Gerenciar contas bancárias e caixas'],
      ['documentos_fiscais', 'Consultar documentos fiscais'],
      ['pedidos_fornecedor', 'Consultar pedidos faturados por fornecedor', null, true],
      ['pagamento_pedidos', 'Gerenciar pagamento de pedidos'],
      ['extrato', 'Consultar extrato financeiro', null, true],
    ],
  },
  {
    key: 'comissoes',
    label: 'Gestão de Comissões',
    icon: 'Percent',
    acoes: [
      ['consultar_proprias', 'Consultar somente a própria comissão'],
      ['consultar_todas', 'Consultar a comissão de todos os funcionários', null, true],
      ['configurar_parametros', 'Configurar parâmetros de comissão'],
      ['configurar_equipes', 'Configurar gerentes e equipes'],
      ['configurar_parametros_equipe', 'Configurar comissão por gerente/equipe'],
      ['apurar', 'Apurar comissões do período'],
      ['pagar', 'Registrar pagamento de comissão'],
    ],
  },
  {
    key: 'marketing',
    label: 'Marketing',
    icon: 'Megaphone',
    acoes: [
      ['acessar', 'Acessar o menu Marketing'],
      ['gerenciar_campanhas', 'Gerenciar campanhas'],
      ['disparar_campanha', 'Disparar campanha'],
      ['consultar_envios', 'Consultar histórico de envios'],
      ['gerenciar_templates', 'Gerenciar modelos de mensagem'],
      ['gerenciar_eventos', 'Gerenciar eventos automáticos'],
      ['gerenciar_promocoes', 'Gerenciar promoções'],
      ['gerenciar_cashback', 'Gerenciar cashback'],
      ['gerenciar_indicacoes', 'Gerenciar indicações'],
      ['gerenciar_vitrine', 'Configurar a vitrine online'],
    ],
  },
  {
    key: 'relatorios',
    label: 'Relatórios',
    icon: 'BarChart3',
    acoes: [
      ['vendas', 'Relatório de vendas'],
      ['produtos_vendidos', 'Relatório de produtos vendidos'],
      ['produtos_sem_giro', 'Relatório de produtos sem giro'],
      ['receitas_vencidas', 'Relatório de receitas vencidas'],
      ['aniversarios', 'Relatório de aniversários'],
      ['extrato_financeiro', 'Relatório de extrato financeiro', null, true],
      ['posicao_estoque', 'Relatório de posição atual do estoque'],
      ['caixas', 'Relatório de caixas', null, true],
      ['contas_pagar', 'Relatório de contas a pagar', null, true],
      ['contas_receber', 'Relatório de contas a receber', null, true],
      ['livro_receitas', 'Livro de receitas'],
      ['comissoes', 'Relatório de comissões', null, true],
      ['comissoes_equipe', 'Relatório de comissões por gerente/equipe', null, true],
      ['validade_produtos', 'Relatório de validade de produtos'],
      ['exportar_excel', 'Exportar relatórios para Excel'],
    ],
  },
  {
    key: 'atendimento',
    label: 'Atendimento',
    icon: 'Handshake',
    acoes: [
      ['acessar', 'Acessar o registro de atendimento'],
      ['registrar', 'Registrar atendimento (inclusive sem venda)'],
      ['alterar', 'Alterar atendimento'],
      ['excluir', 'Excluir atendimento'],
      ['registrar_objecao', 'Registrar objeção'],
      ['registrar_experimentacao', 'Registrar experimentação de armação'],
      ['ver_contra_argumentos', 'Ver a biblioteca de contra-argumento'],
      ['gerenciar_contra_argumentos', 'Gerenciar a biblioteca de contra-argumento'],
      ['ver_kpis', 'Ver KPIs de atendimento e de experimentação → venda'],
    ],
  },
  {
    key: 'inteligencia',
    label: 'Inteligência',
    icon: 'Sparkles',
    acoes: [
      ['acessar', 'Acessar o menu Inteligência'],
      ['funil', 'Ver o funil'],
      ['oportunidade_aberto', 'Ver oportunidade em aberto', null, true],
      ['filas_trabalho', 'Ver filas de trabalho'],
      ['trabalhar_fila', 'Trabalhar uma fila (disparar ação)'],
      ['configurar_filas', 'Configurar filas'],
      ['configurar_holdout', 'Configurar o grupo de controle', 'Mexer no holdout afeta a medição de incremental; a mudança é versionada e não reescreve histórico.'],
      ['ver_atribuicao', 'Ver a atribuição com grupo de controle', null, true],
      ['segundo_par', 'Ver e trabalhar oportunidades de segundo par'],
      ['nbo', 'Usar a próxima melhor oferta'],
      ['crm_familiar', 'Ver e trabalhar o CRM familiar'],
      ['painel_dono', 'Receber o painel proativo do dono', null, true],
      ['planograma', 'Gerenciar planograma'],
      ['auditar_vitrine', 'Auditar vitrine por foto'],
    ],
  },
  {
    key: 'cadastros',
    label: 'Cadastros',
    icon: 'Settings2',
    acoes: [
      ['acessar', 'Acessar o menu Cadastros'],
      ['tabelas_auxiliares', 'Gerenciar tabelas auxiliares'],
      ['fornecedores', 'Gerenciar fornecedores e laboratórios'],
      ['funcionarios', 'Gerenciar funcionários'],
      ['equipes', 'Gerenciar equipes'],
      ['filiais', 'Gerenciar filiais'],
      ['medicos', 'Gerenciar médicos e optometristas'],
      ['feriados', 'Gerenciar feriados'],
      ['integracoes', 'Gerenciar integrações'],
      ['aliquota_automatica', 'Configurar alíquota automática'],
    ],
  },
  {
    key: 'usuarios',
    label: 'Usuários',
    icon: 'UserCog',
    acoes: [
      ['consultar', 'Consultar usuários'],
      ['incluir', 'Incluir usuário'],
      ['alterar', 'Alterar usuário (inclusive limite de desconto e situação)'],
      ['excluir', 'Excluir usuário'],
      ['resetar_senha', 'Resetar senha de usuário'],
    ],
  },
  {
    key: 'permissoes',
    label: 'Permissões',
    icon: 'ShieldCheck',
    acoes: [
      ['consultar', 'Consultar modelos de permissão'],
      ['gerenciar_modelos', 'Criar e editar modelos de permissão'],
      ['atribuir_modelos', 'Atribuir modelos a usuários'],
      ['ver_catalogo', 'Ver o catálogo completo de permissões'],
    ],
  },
  {
    key: 'clube',
    label: 'Clube de fidelidade',
    icon: 'BadgePercent',
    acoes: [
      ['acessar', 'Acessar o menu Clube'],
      ['gerenciar_planos', 'Gerenciar planos do clube'],
      ['gerenciar_beneficios', 'Gerenciar benefícios e o custo de cada um'],
      ['gerenciar_membros', 'Gerenciar membros'],
      ['gerenciar_cobrancas', 'Gerenciar cobrança recorrente'],
      ['ver_custos', 'Ver o custo modelado por benefício', null, true],
    ],
  },
  {
    key: 'assinaturas',
    label: 'Plano e assinaturas',
    icon: 'Receipt',
    acoes: [
      ['consultar', 'Consultar assinaturas'],
      ['ver_plano', 'Ver o plano atual'],
      ['ativar_addon', 'Ativar um add-on'],
      ['cancelar_addon', 'Cancelar um add-on'],
    ],
  },
  {
    key: 'configuracoes',
    label: 'Configurações',
    icon: 'Settings',
    acoes: [
      ['acessar', 'Acessar o menu Configurações'],
      ['dados_empresa', 'Alterar dados da rede'],
      ['politicas', 'Alterar políticas de operação'],
      ['seguranca', 'Alterar configurações de segurança'],
      ['integracoes', 'Alterar credenciais de integração'],
    ],
  },
  {
    key: 'auditoria',
    label: 'Auditoria',
    icon: 'ScrollText',
    acoes: [
      ['consultar', 'Consultar a trilha de auditoria', null, true],
      ['exportar', 'Exportar a trilha de auditoria'],
    ],
  },
];

/**
 * Modelos de permissão criados junto com a rede. A ótica pode editar todos —
 * menos o de proprietário, que é `is_owner` e vive fora do catálogo.
 *
 * Padrões aceitos em `chaves`: `modulo.acao`, `modulo.*`, e `-modulo.acao`
 * para subtrair algo que um curinga anterior já concedeu.
 */
export const modelosPadrao = [
  {
    nome: 'Gerente',
    descricao: 'Opera a loja por completo, menos o que mexe na estrutura da rede.',
    chaves: [
      'dashboard.*', 'clientes.*', 'receitas.*', 'produtos.*', 'tabelas_lentes.*',
      'orcamentos.*', 'vendas.*', 'ordens_servico.*', 'trocas.*', 'estoque.*',
      'caixa.*', 'contas_pagar.*', 'contas_receber.*', 'crediario.*', 'cartao.*',
      'cheques.*', 'boletos.*', 'financeiro.*', 'comissoes.*', 'marketing.*',
      'relatorios.*', 'atendimento.*', 'inteligencia.*', 'clube.*',
      'cadastros.acessar', 'cadastros.tabelas_auxiliares', 'cadastros.fornecedores',
      'cadastros.funcionarios', 'cadastros.medicos', 'cadastros.feriados',
      'usuarios.consultar', 'permissoes.consultar', 'auditoria.consultar',
      '-comissoes.consultar_proprias',
      '-inteligencia.configurar_holdout',
      '-financeiro.configurar_dre',
    ],
  },
  {
    nome: 'Vendedor',
    descricao: 'Atende, orça, vende e acompanha as próprias O.S.',
    chaves: [
      'dashboard.acessar', 'dashboard.card_aniversariantes', 'dashboard.card_receitas_vencidas',
      'dashboard.card_os_entregar',
      'clientes.acessar', 'clientes.consultar', 'clientes.incluir', 'clientes.alterar',
      'clientes.gerenciar_nucleo_familiar',
      'receitas.consultar', 'receitas.incluir', 'receitas.alterar', 'receitas.imprimir',
      'produtos.acessar', 'produtos.consultar',
      'tabelas_lentes.acessar', 'tabelas_lentes.consultar',
      'orcamentos.consultar_proprios', 'orcamentos.incluir', 'orcamentos.alterar',
      'orcamentos.imprimir', 'orcamentos.converter_venda',
      'vendas.consultar_proprias', 'vendas.incluir', 'vendas.imprimir', 'vendas.emitir_nfce',
      'ordens_servico.consultar_proprias', 'ordens_servico.incluir',
      'ordens_servico.alterar_proprias', 'ordens_servico.mover_etapa',
      'ordens_servico.entregar', 'ordens_servico.imprimir',
      'estoque.acessar', 'estoque.posicao_atual',
      'trocas.consultar', 'trocas.iniciar', 'trocas.utilizar_credito',
      'comissoes.consultar_proprias',
      'atendimento.*', 'inteligencia.acessar', 'inteligencia.filas_trabalho',
      'inteligencia.trabalhar_fila', 'inteligencia.segundo_par', 'inteligencia.nbo',
      'inteligencia.crm_familiar',
      'relatorios.produtos_vendidos', 'relatorios.receitas_vencidas', 'relatorios.aniversarios',
      '-atendimento.gerenciar_contra_argumentos',
    ],
  },
  {
    nome: 'Financeiro',
    descricao: 'Cuida de caixa, títulos, cartão, cheque, boleto e resultado.',
    chaves: [
      'dashboard.acessar', 'dashboard.card_contas_pagar', 'dashboard.card_contas_receber',
      'dashboard.card_negativados',
      'clientes.acessar', 'clientes.consultar', 'clientes.ver_credito', 'clientes.negativar',
      'vendas.consultar', 'ordens_servico.consultar',
      'caixa.*', 'contas_pagar.*', 'contas_receber.*', 'crediario.*', 'cartao.*',
      'cheques.*', 'boletos.*', 'cobranca_bancaria.*', 'financeiro.*', 'trocas.*',
      'relatorios.extrato_financeiro', 'relatorios.caixas', 'relatorios.contas_pagar',
      'relatorios.contas_receber', 'relatorios.vendas', 'relatorios.exportar_excel',
      'comissoes.consultar_todas', 'comissoes.apurar', 'comissoes.pagar',
      'auditoria.consultar',
      '-caixa.alterar_saldo_inicial', '-caixa.excluir_lancamento',
    ],
  },
  {
    nome: 'Laboratório',
    descricao: 'Trabalha o pipeline de O.S. — sem acesso comercial ou financeiro.',
    chaves: [
      'dashboard.acessar', 'dashboard.card_os_entregar',
      'ordens_servico.consultar', 'ordens_servico.alterar', 'ordens_servico.mover_etapa',
      'ordens_servico.entregar', 'ordens_servico.imprimir', 'ordens_servico.ver_paineis',
      'clientes.consultar', 'receitas.consultar',
      'produtos.acessar', 'produtos.consultar',
      'estoque.acessar', 'estoque.posicao_atual', 'estoque.historico',
      'estoque.confirmar_transferencia',
    ],
  },
  {
    nome: 'Estoquista',
    descricao: 'Entrada, transferência, inventário e etiquetas.',
    chaves: [
      'dashboard.acessar', 'dashboard.card_estoque_minimo', 'dashboard.card_validade_produtos',
      'produtos.acessar', 'produtos.consultar', 'produtos.incluir', 'produtos.alterar',
      'produtos.alterar_estoque', 'produtos.alterar_validade',
      'estoque.*', 'relatorios.posicao_estoque', 'relatorios.validade_produtos',
      'relatorios.produtos_sem_giro', 'relatorios.exportar_excel',
      'cadastros.acessar', 'cadastros.fornecedores', 'cadastros.tabelas_auxiliares',
      '-estoque.zerar',
    ],
  },
];
