-- =============================================================================
-- VISIO · 03b · Seed do catálogo de permissões e dos modelos padrão
-- =============================================================================
-- GERADO AUTOMATICAMENTE — não edite à mão.
-- Fonte: scripts/permissions-source.mjs · Regenere com: npm run gen:permissions
--
-- 268 chaves em 31 módulos · 5 modelos padrão
-- =============================================================================

insert into public.permissions (key, modulo, acao, label, descricao, sensivel, ordem) values
  ('dashboard.acessar', 'dashboard', 'acessar', 'Acessar o painel', null, false, 0),
  ('dashboard.card_vendas_mes', 'dashboard', 'card_vendas_mes', 'Card: vendas do mês', null, false, 1),
  ('dashboard.card_vendas_12m', 'dashboard', 'card_vendas_12m', 'Card: últimos 12 meses', null, false, 2),
  ('dashboard.card_comparativo_ano', 'dashboard', 'card_comparativo_ano', 'Card: mesmo mês do ano anterior', null, false, 3),
  ('dashboard.card_contas_pagar', 'dashboard', 'card_contas_pagar', 'Card: contas a pagar em aberto', null, true, 4),
  ('dashboard.card_contas_receber', 'dashboard', 'card_contas_receber', 'Card: contas a receber em aberto', null, true, 5),
  ('dashboard.card_aniversariantes', 'dashboard', 'card_aniversariantes', 'Card: aniversariantes da semana', null, false, 6),
  ('dashboard.card_receitas_vencidas', 'dashboard', 'card_receitas_vencidas', 'Card: receitas vencidas', null, false, 7),
  ('dashboard.card_os_entregar', 'dashboard', 'card_os_entregar', 'Card: O.S. a entregar', null, false, 8),
  ('dashboard.card_validade_produtos', 'dashboard', 'card_validade_produtos', 'Card: validade de produtos', null, false, 9),
  ('dashboard.card_estoque_minimo', 'dashboard', 'card_estoque_minimo', 'Card: produtos abaixo do estoque mínimo', null, false, 10),
  ('dashboard.card_negativados', 'dashboard', 'card_negativados', 'Card: clientes negativados', null, false, 11),
  ('dashboard.card_oportunidade_aberto', 'dashboard', 'card_oportunidade_aberto', 'Card: oportunidade em aberto', null, false, 12),
  ('clientes.acessar', 'clientes', 'acessar', 'Acessar o menu Clientes', null, false, 100),
  ('clientes.consultar', 'clientes', 'consultar', 'Consultar clientes', null, false, 101),
  ('clientes.incluir', 'clientes', 'incluir', 'Incluir cliente', null, false, 102),
  ('clientes.alterar', 'clientes', 'alterar', 'Alterar cliente', null, false, 103),
  ('clientes.alterar_nome', 'clientes', 'alterar_nome', 'Alterar o nome de um cliente já cadastrado', null, false, 104),
  ('clientes.excluir', 'clientes', 'excluir', 'Excluir cliente', null, false, 105),
  ('clientes.importar', 'clientes', 'importar', 'Importar clientes em massa', null, false, 106),
  ('clientes.exportar', 'clientes', 'exportar', 'Exportar clientes', null, false, 107),
  ('clientes.exportar_receitas', 'clientes', 'exportar_receitas', 'Exportar receitas', null, false, 108),
  ('clientes.negativar', 'clientes', 'negativar', 'Negativar e remover negativação', null, false, 109),
  ('clientes.ver_credito', 'clientes', 'ver_credito', 'Ver situação de crédito e parcelas em atraso', null, true, 110),
  ('clientes.analise_credito', 'clientes', 'analise_credito', 'Efetuar análise de crédito', 'Exige consentimento do titular; a decisão é sempre revisável por humano.', true, 111),
  ('clientes.gerenciar_nucleo_familiar', 'clientes', 'gerenciar_nucleo_familiar', 'Gerenciar núcleo familiar', null, false, 112),
  ('receitas.consultar', 'receitas', 'consultar', 'Consultar receitas', null, false, 200),
  ('receitas.incluir', 'receitas', 'incluir', 'Incluir receita', null, false, 201),
  ('receitas.alterar', 'receitas', 'alterar', 'Alterar receita', null, false, 202),
  ('receitas.excluir', 'receitas', 'excluir', 'Excluir receita', null, false, 203),
  ('receitas.imprimir', 'receitas', 'imprimir', 'Imprimir receita', null, false, 204),
  ('receitas.livro_receitas', 'receitas', 'livro_receitas', 'Acessar o Livro de Receitas', null, false, 205),
  ('produtos.acessar', 'produtos', 'acessar', 'Acessar o menu Produtos', null, false, 300),
  ('produtos.consultar', 'produtos', 'consultar', 'Consultar produtos', null, false, 301),
  ('produtos.incluir', 'produtos', 'incluir', 'Incluir produto', null, false, 302),
  ('produtos.alterar', 'produtos', 'alterar', 'Alterar dados do produto', null, false, 303),
  ('produtos.excluir', 'produtos', 'excluir', 'Excluir ou arquivar produto', null, false, 304),
  ('produtos.ver_custo', 'produtos', 'ver_custo', 'Ver preço de custo', null, true, 305),
  ('produtos.alterar_custo', 'produtos', 'alterar_custo', 'Alterar preço de custo', null, true, 306),
  ('produtos.alterar_preco', 'produtos', 'alterar_preco', 'Alterar preço de venda', null, false, 307),
  ('produtos.alterar_estoque', 'produtos', 'alterar_estoque', 'Alterar quantidade em estoque', null, false, 308),
  ('produtos.alterar_validade', 'produtos', 'alterar_validade', 'Alterar validade', null, false, 309),
  ('produtos.alterar_fiscal', 'produtos', 'alterar_fiscal', 'Alterar configuração fiscal (NCM, CEST, tributação)', null, false, 310),
  ('produtos.importar', 'produtos', 'importar', 'Importar produtos em massa', null, false, 311),
  ('produtos.exportar', 'produtos', 'exportar', 'Exportar produtos', null, false, 312),
  ('produtos.gerenciar_vitrine', 'produtos', 'gerenciar_vitrine', 'Incluir e remover da vitrine online', null, false, 313),
  ('tabelas_lentes.acessar', 'tabelas_lentes', 'acessar', 'Acessar o menu Tabelas de Lentes', null, false, 400),
  ('tabelas_lentes.consultar', 'tabelas_lentes', 'consultar', 'Consultar tabelas', null, false, 401),
  ('tabelas_lentes.salvar_conferencia', 'tabelas_lentes', 'salvar_conferencia', 'Salvar conferência de produtos', null, false, 402),
  ('tabelas_lentes.concluir_conferencia', 'tabelas_lentes', 'concluir_conferencia', 'Concluir conferência', null, false, 403),
  ('tabelas_lentes.ver_custo_fornecedor', 'tabelas_lentes', 'ver_custo_fornecedor', 'Ver preço de custo do fornecedor', null, true, 404),
  ('tabelas_lentes.excluir_em_conferencia', 'tabelas_lentes', 'excluir_em_conferencia', 'Excluir tabela em conferência', null, false, 405),
  ('orcamentos.consultar', 'orcamentos', 'consultar', 'Consultar todos os orçamentos', null, false, 500),
  ('orcamentos.consultar_proprios', 'orcamentos', 'consultar_proprios', 'Consultar somente os próprios orçamentos', null, false, 501),
  ('orcamentos.incluir', 'orcamentos', 'incluir', 'Incluir orçamento', null, false, 502),
  ('orcamentos.alterar', 'orcamentos', 'alterar', 'Alterar orçamento', null, false, 503),
  ('orcamentos.excluir', 'orcamentos', 'excluir', 'Excluir orçamento', null, false, 504),
  ('orcamentos.imprimir', 'orcamentos', 'imprimir', 'Imprimir orçamento', null, false, 505),
  ('orcamentos.converter_venda', 'orcamentos', 'converter_venda', 'Converter orçamento em venda', null, false, 506),
  ('orcamentos.prorrogar_validade', 'orcamentos', 'prorrogar_validade', 'Prorrogar a validade de um orçamento', null, false, 507),
  ('vendas.consultar', 'vendas', 'consultar', 'Consultar todas as vendas', null, false, 600),
  ('vendas.consultar_proprias', 'vendas', 'consultar_proprias', 'Consultar somente as próprias vendas', null, false, 601),
  ('vendas.incluir', 'vendas', 'incluir', 'Incluir venda', null, false, 602),
  ('vendas.alterar', 'vendas', 'alterar', 'Alterar venda', null, false, 603),
  ('vendas.cancelar', 'vendas', 'cancelar', 'Cancelar venda', 'Exige motivo obrigatório e fica na trilha de auditoria.', false, 604),
  ('vendas.excluir', 'vendas', 'excluir', 'Excluir venda', 'Exige motivo obrigatório e fica na trilha de auditoria.', false, 605),
  ('vendas.duplicar', 'vendas', 'duplicar', 'Duplicar venda', null, false, 606),
  ('vendas.imprimir', 'vendas', 'imprimir', 'Imprimir venda e relatórios', null, false, 607),
  ('vendas.ver_paineis', 'vendas', 'ver_paineis', 'Ver painéis de resumo', null, false, 608),
  ('vendas.ver_margem', 'vendas', 'ver_margem', 'Ver margem de lucro', null, true, 609),
  ('vendas.data_retroativa', 'vendas', 'data_retroativa', 'Lançar com data retroativa', null, false, 610),
  ('vendas.alterar_valor_unitario', 'vendas', 'alterar_valor_unitario', 'Alterar valor unitário do item', null, false, 611),
  ('vendas.autorizar_desconto_distancia', 'vendas', 'autorizar_desconto_distancia', 'Autorizar desconto à distância', null, false, 612),
  ('vendas.alterar_funcionario', 'vendas', 'alterar_funcionario', 'Alterar o funcionário vinculado', null, false, 613),
  ('vendas.alterar_convenio', 'vendas', 'alterar_convenio', 'Alterar o convênio vinculado', null, false, 614),
  ('vendas.alterar_origem', 'vendas', 'alterar_origem', 'Alterar a origem do cliente vinculada', null, false, 615),
  ('vendas.gerenciar_garantia', 'vendas', 'gerenciar_garantia', 'Gerenciar validade do termo de garantia', null, false, 616),
  ('vendas.emitir_nfce', 'vendas', 'emitir_nfce', 'Emitir NFC-e', null, false, 617),
  ('ordens_servico.consultar', 'ordens_servico', 'consultar', 'Consultar todas as O.S.', null, false, 700),
  ('ordens_servico.consultar_proprias', 'ordens_servico', 'consultar_proprias', 'Consultar somente as próprias O.S.', null, false, 701),
  ('ordens_servico.incluir', 'ordens_servico', 'incluir', 'Incluir O.S.', null, false, 702),
  ('ordens_servico.alterar', 'ordens_servico', 'alterar', 'Alterar qualquer O.S.', null, false, 703),
  ('ordens_servico.alterar_proprias', 'ordens_servico', 'alterar_proprias', 'Alterar somente as próprias O.S.', null, false, 704),
  ('ordens_servico.alterar_somente_abertas', 'ordens_servico', 'alterar_somente_abertas', 'Alterar somente O.S. abertas', null, false, 705),
  ('ordens_servico.cancelar', 'ordens_servico', 'cancelar', 'Cancelar O.S.', null, false, 706),
  ('ordens_servico.confirmar_perda', 'ordens_servico', 'confirmar_perda', 'Confirmar O.S. em perda', null, false, 707),
  ('ordens_servico.mover_etapa', 'ordens_servico', 'mover_etapa', 'Mover O.S. entre etapas do Kanban', null, false, 708),
  ('ordens_servico.entregar', 'ordens_servico', 'entregar', 'Entregar O.S.', null, false, 709),
  ('ordens_servico.retornar_entregue', 'ordens_servico', 'retornar_entregue', 'Retornar O.S. entregue para não entregue', null, false, 710),
  ('ordens_servico.alterar_funcionario', 'ordens_servico', 'alterar_funcionario', 'Alterar o funcionário vinculado', null, false, 711),
  ('ordens_servico.imprimir', 'ordens_servico', 'imprimir', 'Imprimir O.S.', null, false, 712),
  ('ordens_servico.ver_paineis', 'ordens_servico', 'ver_paineis', 'Ver painéis de resumo', null, false, 713),
  ('ordens_servico.data_retroativa', 'ordens_servico', 'data_retroativa', 'Abrir ou lançar com data retroativa', null, false, 714),
  ('ordens_servico.gerenciar_etapas', 'ordens_servico', 'gerenciar_etapas', 'Configurar tipos e etapas de O.S. (SLA por etapa)', null, false, 715),
  ('trocas.consultar', 'trocas', 'consultar', 'Consultar trocas', null, false, 800),
  ('trocas.iniciar', 'trocas', 'iniciar', 'Iniciar troca', null, false, 801),
  ('trocas.cancelar', 'trocas', 'cancelar', 'Cancelar troca', null, false, 802),
  ('trocas.utilizar_credito', 'trocas', 'utilizar_credito', 'Utilizar crédito de troca dentro do limite', null, false, 803),
  ('trocas.utilizar_credito_acima_limite', 'trocas', 'utilizar_credito_acima_limite', 'Utilizar crédito de troca acima do limite', null, false, 804),
  ('trocas.devolver_credito', 'trocas', 'devolver_credito', 'Devolver crédito de troca', null, false, 805),
  ('trocas.inutilizar_credito', 'trocas', 'inutilizar_credito', 'Inutilizar crédito de troca', null, false, 806),
  ('estoque.acessar', 'estoque', 'acessar', 'Acessar o menu Estoque', null, false, 900),
  ('estoque.posicao_atual', 'estoque', 'posicao_atual', 'Consultar posição atual', null, false, 901),
  ('estoque.posicao_todas_filiais', 'estoque', 'posicao_todas_filiais', 'Consultar a posição de todas as filiais', null, false, 902),
  ('estoque.entrada_nf', 'estoque', 'entrada_nf', 'Dar entrada por XML de NF-e', null, false, 903),
  ('estoque.entrada_manual', 'estoque', 'entrada_manual', 'Dar entrada manual', null, false, 904),
  ('estoque.transferir', 'estoque', 'transferir', 'Solicitar transferência entre filiais', null, false, 905),
  ('estoque.confirmar_transferencia', 'estoque', 'confirmar_transferencia', 'Confirmar recebimento de transferência', null, false, 906),
  ('estoque.inventario', 'estoque', 'inventario', 'Realizar inventário', null, false, 907),
  ('estoque.acerto', 'estoque', 'acerto', 'Fazer acerto de estoque', null, false, 908),
  ('estoque.etiquetas', 'estoque', 'etiquetas', 'Montar e imprimir etiquetas', null, false, 909),
  ('estoque.historico', 'estoque', 'historico', 'Consultar histórico de movimentação', null, false, 910),
  ('estoque.zerar', 'estoque', 'zerar', 'Zerar estoque', null, false, 911),
  ('estoque.exportar', 'estoque', 'exportar', 'Exportar posição de estoque', null, false, 912),
  ('caixa.consultar', 'caixa', 'consultar', 'Consultar posição atual do caixa', null, true, 1000),
  ('caixa.abrir', 'caixa', 'abrir', 'Abrir caixa', null, false, 1001),
  ('caixa.fechar', 'caixa', 'fechar', 'Fechar caixa', null, false, 1002),
  ('caixa.reabrir', 'caixa', 'reabrir', 'Reabrir caixa fechado', null, false, 1003),
  ('caixa.pagar_despesa', 'caixa', 'pagar_despesa', 'Pagar despesas pelo caixa', null, false, 1004),
  ('caixa.transferir', 'caixa', 'transferir', 'Transferir entre contas', null, false, 1005),
  ('caixa.suprimento', 'caixa', 'suprimento', 'Lançar suprimento', null, false, 1006),
  ('caixa.sangria', 'caixa', 'sangria', 'Lançar sangria', null, false, 1007),
  ('caixa.excluir_lancamento', 'caixa', 'excluir_lancamento', 'Apagar lançamentos', null, false, 1008),
  ('caixa.alterar_saldo_inicial', 'caixa', 'alterar_saldo_inicial', 'Alterar saldo inicial', null, false, 1009),
  ('contas_pagar.consultar', 'contas_pagar', 'consultar', 'Consultar contas a pagar', null, true, 1100),
  ('contas_pagar.incluir', 'contas_pagar', 'incluir', 'Incluir conta a pagar', null, false, 1101),
  ('contas_pagar.alterar', 'contas_pagar', 'alterar', 'Alterar conta a pagar', null, false, 1102),
  ('contas_pagar.baixar', 'contas_pagar', 'baixar', 'Baixar conta a pagar', null, false, 1103),
  ('contas_pagar.estornar', 'contas_pagar', 'estornar', 'Estornar baixa', null, false, 1104),
  ('contas_pagar.cancelar', 'contas_pagar', 'cancelar', 'Cancelar conta a pagar', null, false, 1105),
  ('contas_pagar.imprimir', 'contas_pagar', 'imprimir', 'Imprimir', null, false, 1106),
  ('contas_pagar.data_retroativa', 'contas_pagar', 'data_retroativa', 'Lançar ou baixar com data retroativa', null, false, 1107),
  ('contas_receber.consultar', 'contas_receber', 'consultar', 'Consultar contas a receber', null, true, 1200),
  ('contas_receber.incluir', 'contas_receber', 'incluir', 'Incluir conta a receber', null, false, 1201),
  ('contas_receber.alterar', 'contas_receber', 'alterar', 'Alterar conta a receber', null, false, 1202),
  ('contas_receber.receber', 'contas_receber', 'receber', 'Receber / baixar', null, false, 1203),
  ('contas_receber.estornar', 'contas_receber', 'estornar', 'Estornar recebimento', null, false, 1204),
  ('contas_receber.cancelar', 'contas_receber', 'cancelar', 'Cancelar conta a receber', null, false, 1205),
  ('contas_receber.imprimir', 'contas_receber', 'imprimir', 'Imprimir', null, false, 1206),
  ('contas_receber.data_retroativa', 'contas_receber', 'data_retroativa', 'Lançar ou receber com data retroativa', null, false, 1207),
  ('contas_receber.alterar_situacao', 'contas_receber', 'alterar_situacao', 'Alterar situação', null, false, 1208),
  ('contas_receber.renegociar', 'contas_receber', 'renegociar', 'Renegociar dívida', null, false, 1209),
  ('contas_receber.autorizar_desconto_distancia', 'contas_receber', 'autorizar_desconto_distancia', 'Autorizar desconto à distância', null, false, 1210),
  ('contas_receber.baixar_outras_filiais', 'contas_receber', 'baixar_outras_filiais', 'Baixar títulos de outras filiais da rede', null, false, 1211),
  ('crediario.consultar', 'crediario', 'consultar', 'Consultar crediários', null, true, 1300),
  ('crediario.conceder', 'crediario', 'conceder', 'Conceder crediário', null, false, 1301),
  ('crediario.alterar_limite', 'crediario', 'alterar_limite', 'Alterar limite do cliente', null, false, 1302),
  ('crediario.baixar', 'crediario', 'baixar', 'Baixar parcela de crediário', null, false, 1303),
  ('crediario.ver_score', 'crediario', 'ver_score', 'Ver score e histórico de análise de crédito', null, true, 1304),
  ('cartao.consultar', 'cartao', 'consultar', 'Consultar recebimentos de cartão', null, true, 1400),
  ('cartao.conciliar', 'cartao', 'conciliar', 'Conciliar com a adquirente', null, false, 1401),
  ('cartao.gerenciar_antecipacoes', 'cartao', 'gerenciar_antecipacoes', 'Gerenciar antecipações', null, false, 1402),
  ('cartao.alterar_taxa', 'cartao', 'alterar_taxa', 'Alterar taxa', null, false, 1403),
  ('cartao.ver_liquido', 'cartao', 'ver_liquido', 'Ver valor líquido e taxa descontada', null, true, 1404),
  ('cheques.consultar', 'cheques', 'consultar', 'Consultar cheques', null, true, 1500),
  ('cheques.incluir', 'cheques', 'incluir', 'Incluir cheque', null, false, 1501),
  ('cheques.alterar_status', 'cheques', 'alterar_status', 'Alterar status (depositado, compensado, devolvido)', null, false, 1502),
  ('cheques.devolver', 'cheques', 'devolver', 'Registrar devolução', null, false, 1503),
  ('cheques.imprimir', 'cheques', 'imprimir', 'Imprimir', null, false, 1504),
  ('boletos.consultar', 'boletos', 'consultar', 'Consultar boletos', null, true, 1600),
  ('boletos.emitir', 'boletos', 'emitir', 'Emitir boleto', null, false, 1601),
  ('boletos.cancelar', 'boletos', 'cancelar', 'Cancelar boleto', null, false, 1602),
  ('boletos.baixar', 'boletos', 'baixar', 'Baixar boleto', null, false, 1603),
  ('boletos.ver_taxas', 'boletos', 'ver_taxas', 'Ver taxas de emissão', null, true, 1604),
  ('cobranca_bancaria.consultar', 'cobranca_bancaria', 'consultar', 'Consultar remessas e retornos', null, true, 1700),
  ('cobranca_bancaria.gerar_remessa', 'cobranca_bancaria', 'gerar_remessa', 'Gerar arquivo de remessa (CNAB)', null, false, 1701),
  ('cobranca_bancaria.processar_retorno', 'cobranca_bancaria', 'processar_retorno', 'Processar arquivo de retorno (CNAB)', null, false, 1702),
  ('cobranca_bancaria.configurar', 'cobranca_bancaria', 'configurar', 'Configurar convênio de cobrança', null, false, 1703),
  ('financeiro.fluxo_financeiro', 'financeiro', 'fluxo_financeiro', 'Consultar fluxo financeiro (previsto e realizado)', null, true, 1800),
  ('financeiro.dre', 'financeiro', 'dre', 'Consultar Resultado (DRE)', null, true, 1801),
  ('financeiro.configurar_dre', 'financeiro', 'configurar_dre', 'Configurar o DRE', null, false, 1802),
  ('financeiro.plano_contas', 'financeiro', 'plano_contas', 'Gerenciar plano de contas', null, false, 1803),
  ('financeiro.contas_bancarias', 'financeiro', 'contas_bancarias', 'Gerenciar contas bancárias e caixas', null, false, 1804),
  ('financeiro.documentos_fiscais', 'financeiro', 'documentos_fiscais', 'Consultar documentos fiscais', null, false, 1805),
  ('financeiro.pedidos_fornecedor', 'financeiro', 'pedidos_fornecedor', 'Consultar pedidos faturados por fornecedor', null, true, 1806),
  ('financeiro.pagamento_pedidos', 'financeiro', 'pagamento_pedidos', 'Gerenciar pagamento de pedidos', null, false, 1807),
  ('financeiro.extrato', 'financeiro', 'extrato', 'Consultar extrato financeiro', null, true, 1808),
  ('comissoes.consultar_proprias', 'comissoes', 'consultar_proprias', 'Consultar somente a própria comissão', null, false, 1900),
  ('comissoes.consultar_todas', 'comissoes', 'consultar_todas', 'Consultar a comissão de todos os funcionários', null, true, 1901),
  ('comissoes.configurar_parametros', 'comissoes', 'configurar_parametros', 'Configurar parâmetros de comissão', null, false, 1902),
  ('comissoes.configurar_equipes', 'comissoes', 'configurar_equipes', 'Configurar gerentes e equipes', null, false, 1903),
  ('comissoes.configurar_parametros_equipe', 'comissoes', 'configurar_parametros_equipe', 'Configurar comissão por gerente/equipe', null, false, 1904),
  ('comissoes.apurar', 'comissoes', 'apurar', 'Apurar comissões do período', null, false, 1905),
  ('comissoes.pagar', 'comissoes', 'pagar', 'Registrar pagamento de comissão', null, false, 1906),
  ('marketing.acessar', 'marketing', 'acessar', 'Acessar o menu Marketing', null, false, 2000),
  ('marketing.gerenciar_campanhas', 'marketing', 'gerenciar_campanhas', 'Gerenciar campanhas', null, false, 2001),
  ('marketing.disparar_campanha', 'marketing', 'disparar_campanha', 'Disparar campanha', null, false, 2002),
  ('marketing.consultar_envios', 'marketing', 'consultar_envios', 'Consultar histórico de envios', null, false, 2003),
  ('marketing.gerenciar_templates', 'marketing', 'gerenciar_templates', 'Gerenciar modelos de mensagem', null, false, 2004),
  ('marketing.gerenciar_eventos', 'marketing', 'gerenciar_eventos', 'Gerenciar eventos automáticos', null, false, 2005),
  ('marketing.gerenciar_promocoes', 'marketing', 'gerenciar_promocoes', 'Gerenciar promoções', null, false, 2006),
  ('marketing.gerenciar_cashback', 'marketing', 'gerenciar_cashback', 'Gerenciar cashback', null, false, 2007),
  ('marketing.gerenciar_indicacoes', 'marketing', 'gerenciar_indicacoes', 'Gerenciar indicações', null, false, 2008),
  ('marketing.gerenciar_vitrine', 'marketing', 'gerenciar_vitrine', 'Configurar a vitrine online', null, false, 2009),
  ('relatorios.vendas', 'relatorios', 'vendas', 'Relatório de vendas', null, false, 2100),
  ('relatorios.produtos_vendidos', 'relatorios', 'produtos_vendidos', 'Relatório de produtos vendidos', null, false, 2101),
  ('relatorios.produtos_sem_giro', 'relatorios', 'produtos_sem_giro', 'Relatório de produtos sem giro', null, false, 2102),
  ('relatorios.receitas_vencidas', 'relatorios', 'receitas_vencidas', 'Relatório de receitas vencidas', null, false, 2103),
  ('relatorios.aniversarios', 'relatorios', 'aniversarios', 'Relatório de aniversários', null, false, 2104),
  ('relatorios.extrato_financeiro', 'relatorios', 'extrato_financeiro', 'Relatório de extrato financeiro', null, true, 2105),
  ('relatorios.posicao_estoque', 'relatorios', 'posicao_estoque', 'Relatório de posição atual do estoque', null, false, 2106),
  ('relatorios.caixas', 'relatorios', 'caixas', 'Relatório de caixas', null, true, 2107),
  ('relatorios.contas_pagar', 'relatorios', 'contas_pagar', 'Relatório de contas a pagar', null, true, 2108),
  ('relatorios.contas_receber', 'relatorios', 'contas_receber', 'Relatório de contas a receber', null, true, 2109),
  ('relatorios.livro_receitas', 'relatorios', 'livro_receitas', 'Livro de receitas', null, false, 2110),
  ('relatorios.comissoes', 'relatorios', 'comissoes', 'Relatório de comissões', null, true, 2111),
  ('relatorios.comissoes_equipe', 'relatorios', 'comissoes_equipe', 'Relatório de comissões por gerente/equipe', null, true, 2112),
  ('relatorios.validade_produtos', 'relatorios', 'validade_produtos', 'Relatório de validade de produtos', null, false, 2113),
  ('relatorios.exportar_excel', 'relatorios', 'exportar_excel', 'Exportar relatórios para Excel', null, false, 2114),
  ('atendimento.acessar', 'atendimento', 'acessar', 'Acessar o registro de atendimento', null, false, 2200),
  ('atendimento.registrar', 'atendimento', 'registrar', 'Registrar atendimento (inclusive sem venda)', null, false, 2201),
  ('atendimento.alterar', 'atendimento', 'alterar', 'Alterar atendimento', null, false, 2202),
  ('atendimento.excluir', 'atendimento', 'excluir', 'Excluir atendimento', null, false, 2203),
  ('atendimento.registrar_objecao', 'atendimento', 'registrar_objecao', 'Registrar objeção', null, false, 2204),
  ('atendimento.registrar_experimentacao', 'atendimento', 'registrar_experimentacao', 'Registrar experimentação de armação', null, false, 2205),
  ('atendimento.ver_contra_argumentos', 'atendimento', 'ver_contra_argumentos', 'Ver a biblioteca de contra-argumento', null, false, 2206),
  ('atendimento.gerenciar_contra_argumentos', 'atendimento', 'gerenciar_contra_argumentos', 'Gerenciar a biblioteca de contra-argumento', null, false, 2207),
  ('atendimento.ver_kpis', 'atendimento', 'ver_kpis', 'Ver KPIs de atendimento e de experimentação → venda', null, false, 2208),
  ('inteligencia.acessar', 'inteligencia', 'acessar', 'Acessar o menu Inteligência', null, false, 2300),
  ('inteligencia.funil', 'inteligencia', 'funil', 'Ver o funil', null, false, 2301),
  ('inteligencia.oportunidade_aberto', 'inteligencia', 'oportunidade_aberto', 'Ver oportunidade em aberto', null, true, 2302),
  ('inteligencia.filas_trabalho', 'inteligencia', 'filas_trabalho', 'Ver filas de trabalho', null, false, 2303),
  ('inteligencia.trabalhar_fila', 'inteligencia', 'trabalhar_fila', 'Trabalhar uma fila (disparar ação)', null, false, 2304),
  ('inteligencia.configurar_filas', 'inteligencia', 'configurar_filas', 'Configurar filas', null, false, 2305),
  ('inteligencia.configurar_holdout', 'inteligencia', 'configurar_holdout', 'Configurar o grupo de controle', 'Mexer no holdout afeta a medição de incremental; a mudança é versionada e não reescreve histórico.', false, 2306),
  ('inteligencia.ver_atribuicao', 'inteligencia', 'ver_atribuicao', 'Ver a atribuição com grupo de controle', null, true, 2307),
  ('inteligencia.segundo_par', 'inteligencia', 'segundo_par', 'Ver e trabalhar oportunidades de segundo par', null, false, 2308),
  ('inteligencia.nbo', 'inteligencia', 'nbo', 'Usar a próxima melhor oferta', null, false, 2309),
  ('inteligencia.crm_familiar', 'inteligencia', 'crm_familiar', 'Ver e trabalhar o CRM familiar', null, false, 2310),
  ('inteligencia.painel_dono', 'inteligencia', 'painel_dono', 'Receber o painel proativo do dono', null, true, 2311),
  ('inteligencia.planograma', 'inteligencia', 'planograma', 'Gerenciar planograma', null, false, 2312),
  ('inteligencia.auditar_vitrine', 'inteligencia', 'auditar_vitrine', 'Auditar vitrine por foto', null, false, 2313),
  ('cadastros.acessar', 'cadastros', 'acessar', 'Acessar o menu Cadastros', null, false, 2400),
  ('cadastros.tabelas_auxiliares', 'cadastros', 'tabelas_auxiliares', 'Gerenciar tabelas auxiliares', null, false, 2401),
  ('cadastros.fornecedores', 'cadastros', 'fornecedores', 'Gerenciar fornecedores e laboratórios', null, false, 2402),
  ('cadastros.funcionarios', 'cadastros', 'funcionarios', 'Gerenciar funcionários', null, false, 2403),
  ('cadastros.equipes', 'cadastros', 'equipes', 'Gerenciar equipes', null, false, 2404),
  ('cadastros.filiais', 'cadastros', 'filiais', 'Gerenciar filiais', null, false, 2405),
  ('cadastros.medicos', 'cadastros', 'medicos', 'Gerenciar médicos e optometristas', null, false, 2406),
  ('cadastros.feriados', 'cadastros', 'feriados', 'Gerenciar feriados', null, false, 2407),
  ('cadastros.integracoes', 'cadastros', 'integracoes', 'Gerenciar integrações', null, false, 2408),
  ('cadastros.aliquota_automatica', 'cadastros', 'aliquota_automatica', 'Configurar alíquota automática', null, false, 2409),
  ('usuarios.consultar', 'usuarios', 'consultar', 'Consultar usuários', null, false, 2500),
  ('usuarios.incluir', 'usuarios', 'incluir', 'Incluir usuário', null, false, 2501),
  ('usuarios.alterar', 'usuarios', 'alterar', 'Alterar usuário (inclusive limite de desconto e situação)', null, false, 2502),
  ('usuarios.excluir', 'usuarios', 'excluir', 'Excluir usuário', null, false, 2503),
  ('usuarios.resetar_senha', 'usuarios', 'resetar_senha', 'Resetar senha de usuário', null, false, 2504),
  ('permissoes.consultar', 'permissoes', 'consultar', 'Consultar modelos de permissão', null, false, 2600),
  ('permissoes.gerenciar_modelos', 'permissoes', 'gerenciar_modelos', 'Criar e editar modelos de permissão', null, false, 2601),
  ('permissoes.atribuir_modelos', 'permissoes', 'atribuir_modelos', 'Atribuir modelos a usuários', null, false, 2602),
  ('permissoes.ver_catalogo', 'permissoes', 'ver_catalogo', 'Ver o catálogo completo de permissões', null, false, 2603),
  ('clube.acessar', 'clube', 'acessar', 'Acessar o menu Clube', null, false, 2700),
  ('clube.gerenciar_planos', 'clube', 'gerenciar_planos', 'Gerenciar planos do clube', null, false, 2701),
  ('clube.gerenciar_beneficios', 'clube', 'gerenciar_beneficios', 'Gerenciar benefícios e o custo de cada um', null, false, 2702),
  ('clube.gerenciar_membros', 'clube', 'gerenciar_membros', 'Gerenciar membros', null, false, 2703),
  ('clube.gerenciar_cobrancas', 'clube', 'gerenciar_cobrancas', 'Gerenciar cobrança recorrente', null, false, 2704),
  ('clube.ver_custos', 'clube', 'ver_custos', 'Ver o custo modelado por benefício', null, true, 2705),
  ('assinaturas.consultar', 'assinaturas', 'consultar', 'Consultar assinaturas', null, false, 2800),
  ('assinaturas.ver_plano', 'assinaturas', 'ver_plano', 'Ver o plano atual', null, false, 2801),
  ('assinaturas.ativar_addon', 'assinaturas', 'ativar_addon', 'Ativar um add-on', null, false, 2802),
  ('assinaturas.cancelar_addon', 'assinaturas', 'cancelar_addon', 'Cancelar um add-on', null, false, 2803),
  ('configuracoes.acessar', 'configuracoes', 'acessar', 'Acessar o menu Configurações', null, false, 2900),
  ('configuracoes.dados_empresa', 'configuracoes', 'dados_empresa', 'Alterar dados da rede', null, false, 2901),
  ('configuracoes.politicas', 'configuracoes', 'politicas', 'Alterar políticas de operação', null, false, 2902),
  ('configuracoes.seguranca', 'configuracoes', 'seguranca', 'Alterar configurações de segurança', null, false, 2903),
  ('configuracoes.integracoes', 'configuracoes', 'integracoes', 'Alterar credenciais de integração', null, false, 2904),
  ('auditoria.consultar', 'auditoria', 'consultar', 'Consultar a trilha de auditoria', null, true, 3000),
  ('auditoria.exportar', 'auditoria', 'exportar', 'Exportar a trilha de auditoria', null, false, 3001)
on conflict (key) do update set
  modulo    = excluded.modulo,
  acao      = excluded.acao,
  label     = excluded.label,
  descricao = excluded.descricao,
  sensivel  = excluded.sensivel,
  ordem     = excluded.ordem;

-- Chaves que saíram do catálogo em uma versão nova do software deixam de existir;
-- o ON DELETE CASCADE da FK limpa as atribuições que as referenciavam.
delete from public.permissions
 where key not in (
   'dashboard.acessar',
   'dashboard.card_vendas_mes',
   'dashboard.card_vendas_12m',
   'dashboard.card_comparativo_ano',
   'dashboard.card_contas_pagar',
   'dashboard.card_contas_receber',
   'dashboard.card_aniversariantes',
   'dashboard.card_receitas_vencidas',
   'dashboard.card_os_entregar',
   'dashboard.card_validade_produtos',
   'dashboard.card_estoque_minimo',
   'dashboard.card_negativados',
   'dashboard.card_oportunidade_aberto',
   'clientes.acessar',
   'clientes.consultar',
   'clientes.incluir',
   'clientes.alterar',
   'clientes.alterar_nome',
   'clientes.excluir',
   'clientes.importar',
   'clientes.exportar',
   'clientes.exportar_receitas',
   'clientes.negativar',
   'clientes.ver_credito',
   'clientes.analise_credito',
   'clientes.gerenciar_nucleo_familiar',
   'receitas.consultar',
   'receitas.incluir',
   'receitas.alterar',
   'receitas.excluir',
   'receitas.imprimir',
   'receitas.livro_receitas',
   'produtos.acessar',
   'produtos.consultar',
   'produtos.incluir',
   'produtos.alterar',
   'produtos.excluir',
   'produtos.ver_custo',
   'produtos.alterar_custo',
   'produtos.alterar_preco',
   'produtos.alterar_estoque',
   'produtos.alterar_validade',
   'produtos.alterar_fiscal',
   'produtos.importar',
   'produtos.exportar',
   'produtos.gerenciar_vitrine',
   'tabelas_lentes.acessar',
   'tabelas_lentes.consultar',
   'tabelas_lentes.salvar_conferencia',
   'tabelas_lentes.concluir_conferencia',
   'tabelas_lentes.ver_custo_fornecedor',
   'tabelas_lentes.excluir_em_conferencia',
   'orcamentos.consultar',
   'orcamentos.consultar_proprios',
   'orcamentos.incluir',
   'orcamentos.alterar',
   'orcamentos.excluir',
   'orcamentos.imprimir',
   'orcamentos.converter_venda',
   'orcamentos.prorrogar_validade',
   'vendas.consultar',
   'vendas.consultar_proprias',
   'vendas.incluir',
   'vendas.alterar',
   'vendas.cancelar',
   'vendas.excluir',
   'vendas.duplicar',
   'vendas.imprimir',
   'vendas.ver_paineis',
   'vendas.ver_margem',
   'vendas.data_retroativa',
   'vendas.alterar_valor_unitario',
   'vendas.autorizar_desconto_distancia',
   'vendas.alterar_funcionario',
   'vendas.alterar_convenio',
   'vendas.alterar_origem',
   'vendas.gerenciar_garantia',
   'vendas.emitir_nfce',
   'ordens_servico.consultar',
   'ordens_servico.consultar_proprias',
   'ordens_servico.incluir',
   'ordens_servico.alterar',
   'ordens_servico.alterar_proprias',
   'ordens_servico.alterar_somente_abertas',
   'ordens_servico.cancelar',
   'ordens_servico.confirmar_perda',
   'ordens_servico.mover_etapa',
   'ordens_servico.entregar',
   'ordens_servico.retornar_entregue',
   'ordens_servico.alterar_funcionario',
   'ordens_servico.imprimir',
   'ordens_servico.ver_paineis',
   'ordens_servico.data_retroativa',
   'ordens_servico.gerenciar_etapas',
   'trocas.consultar',
   'trocas.iniciar',
   'trocas.cancelar',
   'trocas.utilizar_credito',
   'trocas.utilizar_credito_acima_limite',
   'trocas.devolver_credito',
   'trocas.inutilizar_credito',
   'estoque.acessar',
   'estoque.posicao_atual',
   'estoque.posicao_todas_filiais',
   'estoque.entrada_nf',
   'estoque.entrada_manual',
   'estoque.transferir',
   'estoque.confirmar_transferencia',
   'estoque.inventario',
   'estoque.acerto',
   'estoque.etiquetas',
   'estoque.historico',
   'estoque.zerar',
   'estoque.exportar',
   'caixa.consultar',
   'caixa.abrir',
   'caixa.fechar',
   'caixa.reabrir',
   'caixa.pagar_despesa',
   'caixa.transferir',
   'caixa.suprimento',
   'caixa.sangria',
   'caixa.excluir_lancamento',
   'caixa.alterar_saldo_inicial',
   'contas_pagar.consultar',
   'contas_pagar.incluir',
   'contas_pagar.alterar',
   'contas_pagar.baixar',
   'contas_pagar.estornar',
   'contas_pagar.cancelar',
   'contas_pagar.imprimir',
   'contas_pagar.data_retroativa',
   'contas_receber.consultar',
   'contas_receber.incluir',
   'contas_receber.alterar',
   'contas_receber.receber',
   'contas_receber.estornar',
   'contas_receber.cancelar',
   'contas_receber.imprimir',
   'contas_receber.data_retroativa',
   'contas_receber.alterar_situacao',
   'contas_receber.renegociar',
   'contas_receber.autorizar_desconto_distancia',
   'contas_receber.baixar_outras_filiais',
   'crediario.consultar',
   'crediario.conceder',
   'crediario.alterar_limite',
   'crediario.baixar',
   'crediario.ver_score',
   'cartao.consultar',
   'cartao.conciliar',
   'cartao.gerenciar_antecipacoes',
   'cartao.alterar_taxa',
   'cartao.ver_liquido',
   'cheques.consultar',
   'cheques.incluir',
   'cheques.alterar_status',
   'cheques.devolver',
   'cheques.imprimir',
   'boletos.consultar',
   'boletos.emitir',
   'boletos.cancelar',
   'boletos.baixar',
   'boletos.ver_taxas',
   'cobranca_bancaria.consultar',
   'cobranca_bancaria.gerar_remessa',
   'cobranca_bancaria.processar_retorno',
   'cobranca_bancaria.configurar',
   'financeiro.fluxo_financeiro',
   'financeiro.dre',
   'financeiro.configurar_dre',
   'financeiro.plano_contas',
   'financeiro.contas_bancarias',
   'financeiro.documentos_fiscais',
   'financeiro.pedidos_fornecedor',
   'financeiro.pagamento_pedidos',
   'financeiro.extrato',
   'comissoes.consultar_proprias',
   'comissoes.consultar_todas',
   'comissoes.configurar_parametros',
   'comissoes.configurar_equipes',
   'comissoes.configurar_parametros_equipe',
   'comissoes.apurar',
   'comissoes.pagar',
   'marketing.acessar',
   'marketing.gerenciar_campanhas',
   'marketing.disparar_campanha',
   'marketing.consultar_envios',
   'marketing.gerenciar_templates',
   'marketing.gerenciar_eventos',
   'marketing.gerenciar_promocoes',
   'marketing.gerenciar_cashback',
   'marketing.gerenciar_indicacoes',
   'marketing.gerenciar_vitrine',
   'relatorios.vendas',
   'relatorios.produtos_vendidos',
   'relatorios.produtos_sem_giro',
   'relatorios.receitas_vencidas',
   'relatorios.aniversarios',
   'relatorios.extrato_financeiro',
   'relatorios.posicao_estoque',
   'relatorios.caixas',
   'relatorios.contas_pagar',
   'relatorios.contas_receber',
   'relatorios.livro_receitas',
   'relatorios.comissoes',
   'relatorios.comissoes_equipe',
   'relatorios.validade_produtos',
   'relatorios.exportar_excel',
   'atendimento.acessar',
   'atendimento.registrar',
   'atendimento.alterar',
   'atendimento.excluir',
   'atendimento.registrar_objecao',
   'atendimento.registrar_experimentacao',
   'atendimento.ver_contra_argumentos',
   'atendimento.gerenciar_contra_argumentos',
   'atendimento.ver_kpis',
   'inteligencia.acessar',
   'inteligencia.funil',
   'inteligencia.oportunidade_aberto',
   'inteligencia.filas_trabalho',
   'inteligencia.trabalhar_fila',
   'inteligencia.configurar_filas',
   'inteligencia.configurar_holdout',
   'inteligencia.ver_atribuicao',
   'inteligencia.segundo_par',
   'inteligencia.nbo',
   'inteligencia.crm_familiar',
   'inteligencia.painel_dono',
   'inteligencia.planograma',
   'inteligencia.auditar_vitrine',
   'cadastros.acessar',
   'cadastros.tabelas_auxiliares',
   'cadastros.fornecedores',
   'cadastros.funcionarios',
   'cadastros.equipes',
   'cadastros.filiais',
   'cadastros.medicos',
   'cadastros.feriados',
   'cadastros.integracoes',
   'cadastros.aliquota_automatica',
   'usuarios.consultar',
   'usuarios.incluir',
   'usuarios.alterar',
   'usuarios.excluir',
   'usuarios.resetar_senha',
   'permissoes.consultar',
   'permissoes.gerenciar_modelos',
   'permissoes.atribuir_modelos',
   'permissoes.ver_catalogo',
   'clube.acessar',
   'clube.gerenciar_planos',
   'clube.gerenciar_beneficios',
   'clube.gerenciar_membros',
   'clube.gerenciar_cobrancas',
   'clube.ver_custos',
   'assinaturas.consultar',
   'assinaturas.ver_plano',
   'assinaturas.ativar_addon',
   'assinaturas.cancelar_addon',
   'configuracoes.acessar',
   'configuracoes.dados_empresa',
   'configuracoes.politicas',
   'configuracoes.seguranca',
   'configuracoes.integracoes',
   'auditoria.consultar',
   'auditoria.exportar'
 );

-- -----------------------------------------------------------------------------
-- criar_modelos_padrao — agora com as chaves reais
-- -----------------------------------------------------------------------------
-- Substitui a versão vazia declarada na migration 03, que existia só para o
-- trigger de signup poder referenciá-la antes de o catálogo existir.
create or replace function public.criar_modelos_padrao(p_tenant_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_profile_id uuid;
begin
  -- Gerente: 240 chaves
  insert into public.permission_profiles (tenant_id, nome, descricao)
  values (p_tenant_id, 'Gerente', 'Opera a loja por completo, menos o que mexe na estrutura da rede.')
  returning id into v_profile_id;

  insert into public.permission_profile_permissions (permission_profile_id, permission_key)
  select v_profile_id, k
    from unnest(array[
      'atendimento.acessar',
      'atendimento.alterar',
      'atendimento.excluir',
      'atendimento.gerenciar_contra_argumentos',
      'atendimento.registrar',
      'atendimento.registrar_experimentacao',
      'atendimento.registrar_objecao',
      'atendimento.ver_contra_argumentos',
      'atendimento.ver_kpis',
      'auditoria.consultar',
      'boletos.baixar',
      'boletos.cancelar',
      'boletos.consultar',
      'boletos.emitir',
      'boletos.ver_taxas',
      'cadastros.acessar',
      'cadastros.feriados',
      'cadastros.fornecedores',
      'cadastros.funcionarios',
      'cadastros.medicos',
      'cadastros.tabelas_auxiliares',
      'caixa.abrir',
      'caixa.alterar_saldo_inicial',
      'caixa.consultar',
      'caixa.excluir_lancamento',
      'caixa.fechar',
      'caixa.pagar_despesa',
      'caixa.reabrir',
      'caixa.sangria',
      'caixa.suprimento',
      'caixa.transferir',
      'cartao.alterar_taxa',
      'cartao.conciliar',
      'cartao.consultar',
      'cartao.gerenciar_antecipacoes',
      'cartao.ver_liquido',
      'cheques.alterar_status',
      'cheques.consultar',
      'cheques.devolver',
      'cheques.imprimir',
      'cheques.incluir',
      'clientes.acessar',
      'clientes.alterar',
      'clientes.alterar_nome',
      'clientes.analise_credito',
      'clientes.consultar',
      'clientes.excluir',
      'clientes.exportar',
      'clientes.exportar_receitas',
      'clientes.gerenciar_nucleo_familiar',
      'clientes.importar',
      'clientes.incluir',
      'clientes.negativar',
      'clientes.ver_credito',
      'clube.acessar',
      'clube.gerenciar_beneficios',
      'clube.gerenciar_cobrancas',
      'clube.gerenciar_membros',
      'clube.gerenciar_planos',
      'clube.ver_custos',
      'comissoes.apurar',
      'comissoes.configurar_equipes',
      'comissoes.configurar_parametros',
      'comissoes.configurar_parametros_equipe',
      'comissoes.consultar_todas',
      'comissoes.pagar',
      'contas_pagar.alterar',
      'contas_pagar.baixar',
      'contas_pagar.cancelar',
      'contas_pagar.consultar',
      'contas_pagar.data_retroativa',
      'contas_pagar.estornar',
      'contas_pagar.imprimir',
      'contas_pagar.incluir',
      'contas_receber.alterar',
      'contas_receber.alterar_situacao',
      'contas_receber.autorizar_desconto_distancia',
      'contas_receber.baixar_outras_filiais',
      'contas_receber.cancelar',
      'contas_receber.consultar',
      'contas_receber.data_retroativa',
      'contas_receber.estornar',
      'contas_receber.imprimir',
      'contas_receber.incluir',
      'contas_receber.receber',
      'contas_receber.renegociar',
      'crediario.alterar_limite',
      'crediario.baixar',
      'crediario.conceder',
      'crediario.consultar',
      'crediario.ver_score',
      'dashboard.acessar',
      'dashboard.card_aniversariantes',
      'dashboard.card_comparativo_ano',
      'dashboard.card_contas_pagar',
      'dashboard.card_contas_receber',
      'dashboard.card_estoque_minimo',
      'dashboard.card_negativados',
      'dashboard.card_oportunidade_aberto',
      'dashboard.card_os_entregar',
      'dashboard.card_receitas_vencidas',
      'dashboard.card_validade_produtos',
      'dashboard.card_vendas_12m',
      'dashboard.card_vendas_mes',
      'estoque.acerto',
      'estoque.acessar',
      'estoque.confirmar_transferencia',
      'estoque.entrada_manual',
      'estoque.entrada_nf',
      'estoque.etiquetas',
      'estoque.exportar',
      'estoque.historico',
      'estoque.inventario',
      'estoque.posicao_atual',
      'estoque.posicao_todas_filiais',
      'estoque.transferir',
      'estoque.zerar',
      'financeiro.contas_bancarias',
      'financeiro.documentos_fiscais',
      'financeiro.dre',
      'financeiro.extrato',
      'financeiro.fluxo_financeiro',
      'financeiro.pagamento_pedidos',
      'financeiro.pedidos_fornecedor',
      'financeiro.plano_contas',
      'inteligencia.acessar',
      'inteligencia.auditar_vitrine',
      'inteligencia.configurar_filas',
      'inteligencia.crm_familiar',
      'inteligencia.filas_trabalho',
      'inteligencia.funil',
      'inteligencia.nbo',
      'inteligencia.oportunidade_aberto',
      'inteligencia.painel_dono',
      'inteligencia.planograma',
      'inteligencia.segundo_par',
      'inteligencia.trabalhar_fila',
      'inteligencia.ver_atribuicao',
      'marketing.acessar',
      'marketing.consultar_envios',
      'marketing.disparar_campanha',
      'marketing.gerenciar_campanhas',
      'marketing.gerenciar_cashback',
      'marketing.gerenciar_eventos',
      'marketing.gerenciar_indicacoes',
      'marketing.gerenciar_promocoes',
      'marketing.gerenciar_templates',
      'marketing.gerenciar_vitrine',
      'orcamentos.alterar',
      'orcamentos.consultar',
      'orcamentos.consultar_proprios',
      'orcamentos.converter_venda',
      'orcamentos.excluir',
      'orcamentos.imprimir',
      'orcamentos.incluir',
      'orcamentos.prorrogar_validade',
      'ordens_servico.alterar',
      'ordens_servico.alterar_funcionario',
      'ordens_servico.alterar_proprias',
      'ordens_servico.alterar_somente_abertas',
      'ordens_servico.cancelar',
      'ordens_servico.confirmar_perda',
      'ordens_servico.consultar',
      'ordens_servico.consultar_proprias',
      'ordens_servico.data_retroativa',
      'ordens_servico.entregar',
      'ordens_servico.gerenciar_etapas',
      'ordens_servico.imprimir',
      'ordens_servico.incluir',
      'ordens_servico.mover_etapa',
      'ordens_servico.retornar_entregue',
      'ordens_servico.ver_paineis',
      'permissoes.consultar',
      'produtos.acessar',
      'produtos.alterar',
      'produtos.alterar_custo',
      'produtos.alterar_estoque',
      'produtos.alterar_fiscal',
      'produtos.alterar_preco',
      'produtos.alterar_validade',
      'produtos.consultar',
      'produtos.excluir',
      'produtos.exportar',
      'produtos.gerenciar_vitrine',
      'produtos.importar',
      'produtos.incluir',
      'produtos.ver_custo',
      'receitas.alterar',
      'receitas.consultar',
      'receitas.excluir',
      'receitas.imprimir',
      'receitas.incluir',
      'receitas.livro_receitas',
      'relatorios.aniversarios',
      'relatorios.caixas',
      'relatorios.comissoes',
      'relatorios.comissoes_equipe',
      'relatorios.contas_pagar',
      'relatorios.contas_receber',
      'relatorios.exportar_excel',
      'relatorios.extrato_financeiro',
      'relatorios.livro_receitas',
      'relatorios.posicao_estoque',
      'relatorios.produtos_sem_giro',
      'relatorios.produtos_vendidos',
      'relatorios.receitas_vencidas',
      'relatorios.validade_produtos',
      'relatorios.vendas',
      'tabelas_lentes.acessar',
      'tabelas_lentes.concluir_conferencia',
      'tabelas_lentes.consultar',
      'tabelas_lentes.excluir_em_conferencia',
      'tabelas_lentes.salvar_conferencia',
      'tabelas_lentes.ver_custo_fornecedor',
      'trocas.cancelar',
      'trocas.consultar',
      'trocas.devolver_credito',
      'trocas.iniciar',
      'trocas.inutilizar_credito',
      'trocas.utilizar_credito',
      'trocas.utilizar_credito_acima_limite',
      'usuarios.consultar',
      'vendas.alterar',
      'vendas.alterar_convenio',
      'vendas.alterar_funcionario',
      'vendas.alterar_origem',
      'vendas.alterar_valor_unitario',
      'vendas.autorizar_desconto_distancia',
      'vendas.cancelar',
      'vendas.consultar',
      'vendas.consultar_proprias',
      'vendas.data_retroativa',
      'vendas.duplicar',
      'vendas.emitir_nfce',
      'vendas.excluir',
      'vendas.gerenciar_garantia',
      'vendas.imprimir',
      'vendas.incluir',
      'vendas.ver_margem',
      'vendas.ver_paineis'
    ]::text[]) as k;

  -- Vendedor: 55 chaves
  insert into public.permission_profiles (tenant_id, nome, descricao)
  values (p_tenant_id, 'Vendedor', 'Atende, orça, vende e acompanha as próprias O.S.')
  returning id into v_profile_id;

  insert into public.permission_profile_permissions (permission_profile_id, permission_key)
  select v_profile_id, k
    from unnest(array[
      'atendimento.acessar',
      'atendimento.alterar',
      'atendimento.excluir',
      'atendimento.registrar',
      'atendimento.registrar_experimentacao',
      'atendimento.registrar_objecao',
      'atendimento.ver_contra_argumentos',
      'atendimento.ver_kpis',
      'clientes.acessar',
      'clientes.alterar',
      'clientes.consultar',
      'clientes.gerenciar_nucleo_familiar',
      'clientes.incluir',
      'comissoes.consultar_proprias',
      'dashboard.acessar',
      'dashboard.card_aniversariantes',
      'dashboard.card_os_entregar',
      'dashboard.card_receitas_vencidas',
      'estoque.acessar',
      'estoque.posicao_atual',
      'inteligencia.acessar',
      'inteligencia.crm_familiar',
      'inteligencia.filas_trabalho',
      'inteligencia.nbo',
      'inteligencia.segundo_par',
      'inteligencia.trabalhar_fila',
      'orcamentos.alterar',
      'orcamentos.consultar_proprios',
      'orcamentos.converter_venda',
      'orcamentos.imprimir',
      'orcamentos.incluir',
      'ordens_servico.alterar_proprias',
      'ordens_servico.consultar_proprias',
      'ordens_servico.entregar',
      'ordens_servico.imprimir',
      'ordens_servico.incluir',
      'ordens_servico.mover_etapa',
      'produtos.acessar',
      'produtos.consultar',
      'receitas.alterar',
      'receitas.consultar',
      'receitas.imprimir',
      'receitas.incluir',
      'relatorios.aniversarios',
      'relatorios.produtos_vendidos',
      'relatorios.receitas_vencidas',
      'tabelas_lentes.acessar',
      'tabelas_lentes.consultar',
      'trocas.consultar',
      'trocas.iniciar',
      'trocas.utilizar_credito',
      'vendas.consultar_proprias',
      'vendas.emitir_nfce',
      'vendas.imprimir',
      'vendas.incluir'
    ]::text[]) as k;

  -- Financeiro: 88 chaves
  insert into public.permission_profiles (tenant_id, nome, descricao)
  values (p_tenant_id, 'Financeiro', 'Cuida de caixa, títulos, cartão, cheque, boleto e resultado.')
  returning id into v_profile_id;

  insert into public.permission_profile_permissions (permission_profile_id, permission_key)
  select v_profile_id, k
    from unnest(array[
      'auditoria.consultar',
      'boletos.baixar',
      'boletos.cancelar',
      'boletos.consultar',
      'boletos.emitir',
      'boletos.ver_taxas',
      'caixa.abrir',
      'caixa.consultar',
      'caixa.fechar',
      'caixa.pagar_despesa',
      'caixa.reabrir',
      'caixa.sangria',
      'caixa.suprimento',
      'caixa.transferir',
      'cartao.alterar_taxa',
      'cartao.conciliar',
      'cartao.consultar',
      'cartao.gerenciar_antecipacoes',
      'cartao.ver_liquido',
      'cheques.alterar_status',
      'cheques.consultar',
      'cheques.devolver',
      'cheques.imprimir',
      'cheques.incluir',
      'clientes.acessar',
      'clientes.consultar',
      'clientes.negativar',
      'clientes.ver_credito',
      'cobranca_bancaria.configurar',
      'cobranca_bancaria.consultar',
      'cobranca_bancaria.gerar_remessa',
      'cobranca_bancaria.processar_retorno',
      'comissoes.apurar',
      'comissoes.consultar_todas',
      'comissoes.pagar',
      'contas_pagar.alterar',
      'contas_pagar.baixar',
      'contas_pagar.cancelar',
      'contas_pagar.consultar',
      'contas_pagar.data_retroativa',
      'contas_pagar.estornar',
      'contas_pagar.imprimir',
      'contas_pagar.incluir',
      'contas_receber.alterar',
      'contas_receber.alterar_situacao',
      'contas_receber.autorizar_desconto_distancia',
      'contas_receber.baixar_outras_filiais',
      'contas_receber.cancelar',
      'contas_receber.consultar',
      'contas_receber.data_retroativa',
      'contas_receber.estornar',
      'contas_receber.imprimir',
      'contas_receber.incluir',
      'contas_receber.receber',
      'contas_receber.renegociar',
      'crediario.alterar_limite',
      'crediario.baixar',
      'crediario.conceder',
      'crediario.consultar',
      'crediario.ver_score',
      'dashboard.acessar',
      'dashboard.card_contas_pagar',
      'dashboard.card_contas_receber',
      'dashboard.card_negativados',
      'financeiro.configurar_dre',
      'financeiro.contas_bancarias',
      'financeiro.documentos_fiscais',
      'financeiro.dre',
      'financeiro.extrato',
      'financeiro.fluxo_financeiro',
      'financeiro.pagamento_pedidos',
      'financeiro.pedidos_fornecedor',
      'financeiro.plano_contas',
      'ordens_servico.consultar',
      'relatorios.caixas',
      'relatorios.contas_pagar',
      'relatorios.contas_receber',
      'relatorios.exportar_excel',
      'relatorios.extrato_financeiro',
      'relatorios.vendas',
      'trocas.cancelar',
      'trocas.consultar',
      'trocas.devolver_credito',
      'trocas.iniciar',
      'trocas.inutilizar_credito',
      'trocas.utilizar_credito',
      'trocas.utilizar_credito_acima_limite',
      'vendas.consultar'
    ]::text[]) as k;

  -- Laboratório: 16 chaves
  insert into public.permission_profiles (tenant_id, nome, descricao)
  values (p_tenant_id, 'Laboratório', 'Trabalha o pipeline de O.S. — sem acesso comercial ou financeiro.')
  returning id into v_profile_id;

  insert into public.permission_profile_permissions (permission_profile_id, permission_key)
  select v_profile_id, k
    from unnest(array[
      'clientes.consultar',
      'dashboard.acessar',
      'dashboard.card_os_entregar',
      'estoque.acessar',
      'estoque.confirmar_transferencia',
      'estoque.historico',
      'estoque.posicao_atual',
      'ordens_servico.alterar',
      'ordens_servico.consultar',
      'ordens_servico.entregar',
      'ordens_servico.imprimir',
      'ordens_servico.mover_etapa',
      'ordens_servico.ver_paineis',
      'produtos.acessar',
      'produtos.consultar',
      'receitas.consultar'
    ]::text[]) as k;

  -- Estoquista: 28 chaves
  insert into public.permission_profiles (tenant_id, nome, descricao)
  values (p_tenant_id, 'Estoquista', 'Entrada, transferência, inventário e etiquetas.')
  returning id into v_profile_id;

  insert into public.permission_profile_permissions (permission_profile_id, permission_key)
  select v_profile_id, k
    from unnest(array[
      'cadastros.acessar',
      'cadastros.fornecedores',
      'cadastros.tabelas_auxiliares',
      'dashboard.acessar',
      'dashboard.card_estoque_minimo',
      'dashboard.card_validade_produtos',
      'estoque.acerto',
      'estoque.acessar',
      'estoque.confirmar_transferencia',
      'estoque.entrada_manual',
      'estoque.entrada_nf',
      'estoque.etiquetas',
      'estoque.exportar',
      'estoque.historico',
      'estoque.inventario',
      'estoque.posicao_atual',
      'estoque.posicao_todas_filiais',
      'estoque.transferir',
      'produtos.acessar',
      'produtos.alterar',
      'produtos.alterar_estoque',
      'produtos.alterar_validade',
      'produtos.consultar',
      'produtos.incluir',
      'relatorios.exportar_excel',
      'relatorios.posicao_estoque',
      'relatorios.produtos_sem_giro',
      'relatorios.validade_produtos'
    ]::text[]) as k;

end;
$fn$;

comment on function public.criar_modelos_padrao(uuid) is
  'Cria os modelos de permissão de partida da rede. Editáveis pela ótica; o perfil de proprietário não.';
